### ISSUE TITLE
Rewrite Mercurial-dependent code

### ISSUE THREAD

**Issue by jangler** [jangler/schismtracker#3]
There are places (mostly in build scripts) that rely on the project being a Mercurial repo for optimal behavior. In almost all cases, this seems to be benign, and there are fallbacks if there's no Mercurial repo. A notable exception was the problem fixed by b92bab6.

However, it would be best to figure out which parts of the code are relying on Mercurial info (`git grep -i hg` should be useful here), *why* the code is doing so, and what should be done about it:

1. Modify the code to rely on Git data instead?
2. Just modify the variable/macro names if there's no associated logic?
3. Get rid of the code altogether, leaving only the fallback case?

I like option 3 best if it's practical.

This will probably be an incremental process that should take place on its own branch before being merged into master.

**Comment by mb14** [comment]
Gotta be option 3, I am happy to take as much of this work on as I am able to in a new branch.

**Comment by jangler** [comment]
The one thing I *do* want to keep is some indication in the version string of where the build came from besides "built (date) (time)", which isn't very useful. If you build [the Mercurial version from Bitbucket](https://bitbucket.org/Storlek/schismtracker), you get something like "hg:2015-07-05" in the version string. In a Git repo, you can get the latest commit date in the same format using `git log -n 1 --date=short --format=format:%cd`.

For all my own projects I just have a `VERSION` constant, but Schism hasn't used actual version numbers since ancient times.

**Comment by mb14** [comment]
I am no expert on unix or autotools but looking at Makefile.am:379 it looks we would need a line in Makefile.am something like:
`cflags_version = -DHG_VERSION=\""`(git log -n 1 --date=short --format=format:%cd)`"\"`
?

Quite probably it's not that simple. Of course there also needs to be some logic for people who don't have git, and then we still have a constant called HG_VERSION containing the latest git commit date, but whatever. I will take a look at it all when I get home from work.

**Comment by mb14** [comment]
It wasn't that simple (of course). I think it's pretty much all done now though, would appreciate people (or at least you) trying to build/run the no-hg branch so we can move it into master ASAP.

**Comment by jangler** [comment]
it good
