### ISSUE TITLE
Support importing samples from mp3/m4a/ogg/flac files

### ISSUE THREAD

**Issue by jangler** [jangler/schismtracker#4]
This was pulled from the schismtracker.org wiki TODO list.

Mainly for the purpose of getting it off that list. I'm not actually inclined toward this idea. Being able to import compressed samples would be convenient, but I'm not sure that convenience justifies introducing an additional runtime dependency.

If this were to be implemented, [libsndfile](http://www.mega-nerd.com/libsndfile/) might be of interest, being a popular and relatively small C library that reads Ogg Vorbis and FLAC. Not sure where MP3 and M4A would come from. I don't think we want to get involved with [libavcodec](https://github.com/FFmpeg/FFmpeg/tree/master/libavcodec) or anything else that has a GitHub page saying "Sorry, we had to truncate this directory to 1,000 files."

**Comment by jangler** [comment]
Oh, there's also [SDL_mixer](https://www.libsdl.org/projects/SDL_mixer/release-1.2.html), which might make the most sense.

**Comment by mb14** [comment]
It's a no from me (for the same reasons, in the age of 1TB hard drives I
can't think of much need for compressed samples anyway).

**Comment by jangler** [comment]
I'm just going to close this then.
