### ISSUE TITLE
Statically link SDL?

### ISSUE THREAD

**Issue by jangler** [jangler/schismtracker#5]
I was going to say that the "current" (read: 2012) Linux build of Schism Tracker doesn't actually work for me because it's looking for the wrong/old version of the dynamically linked SDL library. I guess I just said that anyway, but I now have no proof since apparently the archive.org link to the Linux build died overnight (which is scary in itself).

Anyway, statically linking SDL would make distribution easier and more reliable, and I've done it before for another project and don't remember it being that hard. Of course, that wasn't using autoconf/automake and it wasn't targeting multiple operating systems, so I'm not sure how difficult it would be in this case.

**Comment by mb14** [comment]
It's a noble aim, it would make building on Windows a lot harder as
Schism runs like junk unless SDL was compiled with DirectX support, and
I believe that doing that needs Visual Studio. :( 

short term: maybe you can set up the autotools stuff to get it
statitcally linked on Linux, leave it as-is on Windows
long term: maybe we can work out why it runs like junk without DirectX

**Comment by jangler** [comment]
I guess the disadvantage of static linking is that you actually need to have the static library around in order to build, which is a pain compared to the standard operating procedure on Linux.

Especially considering the DirectX obstacle on Windows, I think this is more trouble than it's worth. When we distribute to Windows and OS X, we ship a known-compatible dynamic library with it, and ideally most Linux users can grab Schism from a package manager or build it themselves if the version we distribute doesn't work.

Scrapping this idea.
